sudo: false

language: node_js

node_js:
  - '0.12'

cache:
  directories:
    - node_modules

env:
  global:
    - DEPLOY_BRANCH=master
    - GIT_NAME=Travis-CI
    - GIT_EMAIL=$USER@$(hostname)
    - secure: hsCwvuHU6PbJ77W6P9RQxd2Yvcl/6DZ1x3rUmad6f1uIMnm3/z4TtmUEnxIQAzvPj5pQEEK0G51Mdhh/bRQi9ZEx2XAd/fhDVVvOzbAkNYXrlYm5wfc/jsX7aSbjqWo4Cp9Z5vKC7PlxwByIj/ATg9knhwVkL1Xu1zoKK05yyIa7GMQZSW6PUnUQs2J7Buhdgav9TTacpOJtr4RofjP4a8wO8o0AVhA5XtHY/rOylexKpTlbdujQm9YP1Ehr6RwJ71IbGMMHbnMLOV2KLsBH33vvBT8IgCHXQRdJNGJ+FB4dMmRnNmkII0jdbhEYUl6aHnuojQ6YuR0mWcz1j0vqSIe9q/RZ61+fsdbBdto1U4vrJYaRBA78UsO+EKiLOZYlJg0oY6148nBa8ufLcY4l+mPVecYmuiUfztWRhNUWMz9balK8P0F/kX86lV/uOAL69zEPOlXvEiZoVutNaU1cJ/LXM/DJBMpRSknrm37tgNbqPEo5r+Mjd5Mbl1BChdfQGdDHgD5qLyC7cxczYFUInkv6JI1OpWoxe+zvb//tWuAzUm16JzIqYQFQGleqZgl3DvTYJDPZYmk91X/XSP+LqMyK23QBO1FDuzZx6sQzYOmf/xMkL6+SuUHwiysScSF9zcK2L8E5EUlaWqs6QJPcxTB7y4jnlD4ZvIalTpnyp0g=

before_install:
  - if [[ $DEPLOY_BRANCH == $TRAVIS_BRANCH && $TRAVIS_PULL_REQUEST == "false" ]]; then DO_DEPLOY=true; else DO_DEPLOY=false; fi
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"
  - git config --global credential.helper "store --file=$HOME/.git-credentials"
  - echo https://$GH_TOKEN:@github.com > $HOME/.git-credentials

before_script:
  - if [[ $DO_DEPLOY == "true" ]]; then git config remote.origin.url https://github.com/Ibercheck/api-docs.git; fi

script:
  - gulp

after_script:
  - if [[ $DO_DEPLOY == "true" ]]; then gulp deploy; fi
